# tables.py - per-digit flavour tables for every UWP element.
#
# Each UWP element has its own sub-seed, and each VALUE of each element has
# its own table. Two worlds sharing a digit draw from the same table but
# (almost always) land on different entries, because the pick is seeded by
# the world's unique hash. Add entries freely: picks are independent per
# category, so growing a table never reshuffles other elements - though it
# MAY change future picks within this element for worlds not yet written to
# a dossier (existing dossiers are canon and unaffected).

# ---------------------------------------------------------------- starport

PORT_FLAVOUR = {
    "A": [
        "gleaming concourses and an orbital elevator the locals never stop mentioning",
        "a city in its own right, extraterritorial and smug about it",
        "slick, expensive, and crawling with brokers, spies and headhunters",
        "old imperial architecture, kilometres of marble concourse, impeccable traffic control",
        "a ring of drydocks visible from the ground on clear nights",
        "so busy that berthing is auctioned; tramp captains wait days or pay dearly",
        "immaculate above, labyrinthine below - the service levels have their own economy",
        "run by a port authority prouder than most planetary governments",
    ],
    "B": [
        "busy and competent; the yards run three shifts and the bars never close",
        "a solid working port - freight cranes, crew hostels, honest fuel",
        "prosperous but provincial; the big lines call weekly, not daily",
        "sprawling and modular, grown one prefab annex at a time",
        "renowned for its repair crews - ships limp here from three subsectors",
        "half the port is bonded warehousing; the customs hall is the true centre of power",
        "clean, efficient, and utterly without charm - crews sleep aboard",
        "a proud old port slowly losing traffic to a rival and cutting prices accordingly",
    ],
    "C": [
        "functional concrete aprons, one decent cantina, fuel that needs filtering",
        "a port that has seen better decades and keeps the lights on regardless",
        "adequate - the word that appears in every review",
        "half port, half market; landing fees are negotiable, everything is",
        "run by a family dynasty of portmasters, currently in its third succession dispute",
        "the fuel is cheap, the cranes are old, and the paperwork is optimistic",
        "a wide dirt-and-ferrocrete field ringed by workshops of wildly varying honesty",
        "serviceable by day; after dark it belongs to the loaders' union",
    ],
    "D": [
        "a cracked landing field, a fuel bowser of dubious provenance, a customs shed",
        "one man, one stamp, one price list that changes with his mood",
        "ships land here because they must, not because anyone recommends it",
        "the beacon works most days; the fire crew is a volunteer and his cousin",
        "a downport in name - in practice a paddock with a fence and a flag",
        "everything is for sale except spare parts, which are for barter",
        "the port bar doubles as the customs office, freight exchange and courthouse",
        "recently downgraded, and the staff are still bitter about it",
    ],
    "E": [
        "a beacon, a levelled patch of ground and a windsock's worth of infrastructure",
        "you land, you cope; the locals will trade if you're polite",
        "the 'port' is a tradition of landing in the same flat place",
        "a scorched circle, a cairn of discarded cargo pallets, and silence",
        "marked by an old ship's hull dragged into position as a landmark",
        "the flattest ground for a thousand kilometres, and that is its entire résumé",
    ],
    "X": [
        "no port, no beacon, no welcome - approach is at your own risk",
        "nothing marks the world for landing; that may be deliberate",
        "silence on all traffic bands",
        "the charts say nothing; the last survey noted only 'no facilities' and moved on",
        "whatever port once existed has been erased thoroughly enough to be a statement",
        "approach clearance is not refused - there is simply no one to ask",
    ],
}

# ---------------------------------------------------------------- size

SIZE_FLAVOUR = {
    0: [
        "a tumbling planetoid, all spin-tethers and blasted rock",
        "an irregular rock whose 'day' is a slow tumble on two axes",
        "a captured cometary body, ice pockets still buried in its shadowed craters",
        "a metal-rich shard, magnetic enough to confuse cheap compasses and cheaper pilots",
        "a rubble pile loosely bound by its own gravity; digging is discouraged",
        "one of a scattered cluster - its siblings are visible as bright, slow stars",
    ],
    1: [
        "a moon-sized ball of rock where a strong throw achieves escape velocity, nearly",
        "small enough that the horizon visibly curves at street level",
        "a cratered relic with one hemisphere strangely smoother than the other",
        "so light-gripped that architecture goes up, not out - towers everywhere",
        "a dense little iron world, heavier underfoot than its size suggests",
        "geologically dead for aeons; every scar on its face is ancient history",
    ],
    2: [
        "Luna-sized, grey and sharp-shadowed",
        "a small world of long shallow ridges, like a dried seabed the size of a continent",
        "low gravity gives everyone the local lope - visitors are spotted by their stumble",
        "big enough for weather in its domes, small enough to walk out of its gravity's habit",
        "a pocked, mineral-streaked ball whose sunsets last minutes and stun newcomers",
        "its low gravity breeds tall people and taller cargo stacks",
    ],
    3: [
        "a Mercury-class world of extremes and long horizons",
        "gravity light enough to make freight cheap and bones brittle",
        "a small dense world, all metals, mined in three-kilometre open pits",
        "one great impact basin dominates the northern hemisphere and the folklore",
        "compact and rugged, its mountain ranges out of all proportion to its size",
        "a world you can circumnavigate by grav-belt in a determined week",
    ],
    4: [
        "a small world of big skies and low, old mountains",
        "Mars-adjacent in size and temperament: cold-boned, rusty, patient",
        "light gravity lets the local fliers - mechanical and biological - grow huge",
        "a compact world whose single small sea is the centre of everything",
        "low hills, long dunes, and a horizon close enough to feel private",
        "its modest gravity makes it a favourite retirement world for old belters",
    ],
    5: [
        "a middling world with a split personality: one lush hemisphere, one barren",
        "Mars-sized, with terrain that never learned moderation",
        "gravity at half standard - graceful locals, overconfident visitors",
        "an adolescent world, tectonically restless, growing mountains it doesn't need",
        "compact continents and a single girdling mountain chain",
        "small enough that its weather systems are planet-wide moods",
    ],
    6: [
        "a comfortable seven-tenths gravity that spoils spacers for anywhere else",
        "a mid-sized world of broad plateaus and deeply cut river gorges",
        "big enough for real weather, small enough that everyone shares it",
        "its light gravity and dense core make for strange, beautiful crystal formations",
        "a world of long gentle slopes - nothing here is steep except the politics",
        "moderately sized, immoderately volcanic along its southern arc",
    ],
    7: [
        "nearly a standard world, and touchy about the 'nearly'",
        "rugged and young, with mountain ranges still actively under construction",
        "a well-proportioned world whose geography seems almost designed - some say was",
        "big shield volcanoes anchor its continents like tent pegs",
        "gravity just below standard: everyone arrives feeling slightly heroic",
        "a world of vast weather - storm cells the size of small nations",
    ],
    8: [
        "a standard world in size and gravity; everything else about it is negotiable",
        "Earth-sized, with the deep geology to match - quakes are a season here",
        "a big, slow-turning world of long days and longer shadows",
        "standard gravity, dense core, and a magnetic field that paints the poles with aurora",
        "broad-shouldered and tectonically lively; its maps need frequent revision",
        "exactly the size the textbooks call ideal, which the locals find faintly insulting",
    ],
    9: [
        "a heavy world; a quarter again standard gravity puts iron in the local bones",
        "big and dense - visitors rent exoskeletons, locals pretend not to notice",
        "its extra gravity flattens everything: low buildings, low trees, low tolerance for nonsense",
        "a massive world whose thick crust hoards metals in fat, shallow veins",
        "the gravity breeds squat, powerful fauna and famously stubborn people",
        "everything falls faster here, a fact the orientation brochure over-emphasises",
    ],
    10: [
        "a giant of a world at 1.4g; freight costs shape the whole culture",
        "huge and heavy - its people are short, strong, and quietly contemptuous of tourists",
        "so large its curvature hides weather that would terrify a smaller world",
        "a superterrestrial slab of a planet, rich in everything except comfort",
        "the gravity makes lifting cheap things expensive and expensive things structural",
        "vast, heavy, and slow to change - like its geology, so its institutions",
    ],
}
for _k in range(11, 16):
    SIZE_FLAVOUR[_k] = [
        "a crushing super-earth; unassisted humans tire within the hour",
        "a giant world where grav-plates are infrastructure, not luxury",
        "so massive its mountain ranges are geologically forbidden from ambition",
        "a high-gravity titan settled only because something here is worth it",
        "everything built here is a bunker whether intended or not",
        "its gravity well makes every launch an economic event",
    ]

# ---------------------------------------------------------------- atmosphere

ATMO_FLAVOUR = {
    0: [
        "airless and silent; dust kicked up by landings hangs in ballistic arcs",
        "hard vacuum under a sky of unblinking stars, day and night alike",
        "a vacuum world where footprints from the first survey are still crisp",
        "no air, no sound, no weather - only temperature, and plenty of that",
        "static cling and abrasive dust are the true local hazards",
        "the sky is black at noon; sunrise is a line of fire racing across the plain",
        "vacuum so clean the port sells it, bottled, as a novelty",
        "meteoroids arrive unannounced; every roof is rated and every insurer rich",
    ],
    1: [
        "a trace atmosphere, enough to haze the horizon and lift the dust, no more",
        "air pressure measured in fractions of nothing; suits stay sealed",
        "just enough gas for thin, high, silver clouds that promise nothing",
        "enough atmosphere to carry sound faintly - the wind whispers, barely",
        "twilights are sudden and violet; the trace air scatters one colour only",
        "a wisp of an atmosphere, slowly leaking to space, geologically doomed",
        "dust devils a hundred metres tall wander the plains like lost ghosts",
        "the trace air is pure outgassed argon - useless, but it photographs beautifully",
    ],
    2: [
        "very thin and tainted - sulphur compounds that eat filter cartridges",
        "a mean scrap of air laced with fine silicate dust; lungs need not apply",
        "very thin, with a metallic taint that corrodes seals and tempers alike",
        "barely-there air carrying spores that do nothing good to human tissue",
        "thin, acrid, and prone to electrostatic haze storms",
        "the taint is industrial - somebody polluted this sky and left",
        "a thin poison-laced atmosphere; the vegetation evolved to like it",
        "respirator country: the taint is mild, cumulative, and patient",
    ],
    3: [
        "very thin air, clean but useless - like breathing at nine kilometres",
        "a thin cold gasp of an atmosphere; compressors run everywhere, always",
        "clear thin air with visibility that makes distances lie",
        "so thin that fires sulk and engines wheeze, but sunsets are diamond-sharp",
        "thin air that carries smells strangely far - the port reeks of fuel a valley away",
        "high-altitude world: everyone lives with a respirator hanging at their collar",
        "the thin air makes for huge slow flying creatures and hugger-mugger weather",
        "thin, dry, and static-charged; hair and tempers stand on end",
    ],
    4: [
        "thin and tainted - a biological haze the filters mostly handle",
        "breathable with a filter mask; the pollen here is ambitious",
        "thin air with a heavy-metal dust taint from ancient volcanism",
        "the taint blooms seasonally; locals check the spore forecast like weather",
        "thin, tainted air that smells faintly of almonds - the safety briefing is emphatic",
        "filter-mask country, though old-timers claim immunity and shorter lives",
        "an acid haze taints the thin air downwind of the equatorial vents",
        "thin and gritty; masks are fashion items with tribal significance",
    ],
    5: [
        "thin but clean; newcomers pant for a week and then forget about it",
        "crisp mountain-summit air at sea level, everywhere, always",
        "thin air under a deep indigo sky; stars are visible at midday near the poles",
        "thin and bone-dry; humidifiers are as standard as door handles",
        "the thin air makes storms fast, brief and theatrical",
        "clean thin air that carries sound poorly - locals stand close and speak softly",
        "thin, cold, invigorating; the tourist board says 'bracing' and means it",
        "acclimatisation takes days; the port sells oxygen sachets at honest prices",
    ],
    6: [
        "standard air under a sky that behaves - the meteorologists are bored",
        "a textbook atmosphere with photogenic clouds and reliable rain",
        "standard, humid, and thunderstorm-prone along the coasts",
        "clean standard air with a pollen season that locals call 'the yellow'",
        "standard pressure, high oxygen at the margin - fires burn eagerly here",
        "mild air, huge skies, and cloud formations that feature on postcards",
        "a generous atmosphere with a haze of sea salt that rusts everything lovable",
        "standard and stable, save for a planet-girdling jetstream the pilots respect",
    ],
    7: [
        "breathable but tainted - volcanic sulphur that arrives on the west wind",
        "standard air, spoiled by a biological taint that flares in the warm season",
        "a good atmosphere with one flaw: airborne microspores that scar lungs slowly",
        "the taint is regional; the highlands breathe free and look down on the mask-wearers",
        "standard pressure, tainted by industrial fallout from a war nobody won",
        "the air is fine except after rain, which is often",
        "a rich atmosphere with a heavy-pollen taint; the port pharmacy makes a fortune",
        "tainted standard air - the masks are thin, cheap, and universally resented",
    ],
    8: [
        "dense, soupy air that makes weak flyers of heavy things",
        "a thick atmosphere: slow weather, deep sounds, sunsets like furnace doors",
        "dense air under a permanently pearled sky; shadows are soft here",
        "thick, humid air you can lean on; wings and rumours both travel well",
        "dense and calm - the pressure flattens storms into vast slow swells of cloud",
        "the thick air carries the port's noise to the horizon; silence is a luxury good",
        "dense atmosphere, gloriously breathable, faintly intoxicating at sea level",
        "heavy air that makes newcomers feel every one of their years, briefly",
    ],
    9: [
        "dense and tainted - a chemical haze that turns sunsets apocalyptic",
        "thick air with a corrosive salt taint off the chemical seas",
        "a dense tainted atmosphere; filter masks below the plateau line, by law",
        "heavy air laced with volcanic smog; the taint is worst when the calderas whisper",
        "dense, warm, and tainted with something the surveys still argue about",
        "the thick taint eats paint, lungs and property values in that order",
        "a dense atmosphere whose taint is merely disgusting rather than deadly - officially",
        "heavy tainted air; the rich live upslope, as the rich do",
    ],
    10: [
        "an exotic nitrogen-methane sky, orange-brown and utterly unbreathable",
        "a carbon-dioxide furnace of an atmosphere; airpacks and stubbornness required",
        "exotic air, mostly ammonia, that smells of nothing because you never smell it",
        "a hydrocarbon smog atmosphere that rains something like paraffin",
        "dense noble-gas air, chemically aloof, breathless and strange",
        "an exotic atmosphere with slow, vast convection cells - weather in geological time",
        "unbreathable but placid: the sky is lethal and never once dramatic about it",
        "an exotic mix that supports a native biochemistry with opinions about intruders",
    ],
    11: [
        "a corrosive atmosphere that reduces unprotected metal to lace within weeks",
        "chlorine-green skies over a landscape etched clean of softness",
        "corrosive acid hazes; every airlock has a wash-down bay and a shrine",
        "the air attacks seals, hoses and morale, roughly in that order",
        "a corrosive soup with beautiful copper-salt sunsets that no one watches bare-eyed",
        "hostile air: excursions are engineering projects, not walks",
        "corrosive storms strip paint by night; hulls here wear sacrificial skins",
        "the atmosphere is patient acid; maintenance schedules are scripture",
    ],
    12: [
        "an insidious atmosphere that finds the flaw in any suit, given time",
        "air that defeats protection by hours - the surface duty clock is law",
        "insidious pressure-and-acid conditions; surface work is done by machines and the desperate",
        "the atmosphere infiltrates, corrodes and lies; sensor ghosts are standard",
        "a killing sky - superheated, corrosive, and clingy; nothing surfaces twice unchanged",
        "insidious air that has claimed every generation's monument to having beaten it",
        "conditions so hostile the safety briefing is a signed legal document",
        "the world's true government is the maintenance schedule that keeps the air out",
    ],
    13: [
        "a dense-high atmosphere: unbreathable swamp below, breathable heights above",
        "the air is only human-usable on the plateaus; the lowlands belong to the haze",
        "dense at datum, liveable at altitude - civilisation happens above the cloud floor",
        "the population lives on mesas rising from an ocean of unbreathable murk",
        "a layered sky: the border between good air and bad is visible, and moves",
        "breathable only upslope; downhill is wilderness by atmospheric decree",
    ],
    14: [
        "a thin-low atmosphere pooled in the deeps; the uplands are effectively vacuum",
        "breathable air exists only in canyons and basins - the surface is a suit zone",
        "the world's air hides in its lowlands like water in a dry land",
        "rift-valley civilisation: the breathable strip is mapped to the metre",
        "air pools in the deep places; altitude is measured in minutes of consciousness",
        "a low-air world - climbing a hill is a life-support decision",
    ],
    15: [
        "an unusual atmosphere the surveys describe with footnotes and disagreements",
        "the air changes seasonally between breathable and briefly not",
        "layered gases that stratify strangely; local pilots carry charts of the sky itself",
        "an atmosphere with a slow planet-wide circulation that concentrates its taint in one hemisphere",
        "air that is technically breathable and practically a acquired skill",
        "an ellipsoidal envelope - thick at the equator, near-vacuum at the poles",
    ],
}

# ---------------------------------------------------------------- hydrographics

HYDRO_FLAVOUR = {
    0: [
        "not a drop of standing water on the surface - all of it is bought, mined or remembered",
        "a desert world where water is currency, dowry and casus belli",
        "dry to the bedrock; the great aquifer maps are state secrets",
        "waterless - the ice caps of neighbouring worlds feature in local mythology",
        "its rivers are fossils, its lakes are salt scars, its rain is a rumour",
        "a bone-dry world that measures wealth in recycler efficiency",
    ],
    1: [
        "a single modest sea and a planet of dust jealously arranged around it",
        "scattered brine lakes, briefly doubled by the melt season",
        "one water source worth the name; everything else is pipeline politics",
        "oases strung like beads along the one great fault line",
        "ten percent water, ninety percent argument about it",
        "a dry world with one improbable freshwater sea, guarded like a heart",
    ],
    2: [
        "shallow seas pooled in old craters, shrinking by inches a century",
        "a dry world veined with seasonal rivers that arrive like festivals",
        "small seas, huge deserts, and ports wherever the two meet",
        "water enough for cities but not for carelessness",
        "twin landlocked seas, saltier than blood, mined for their chemistry",
        "the coasts are thin green lines drawn on a vast dry canvas",
    ],
    3: [
        "a dry world by any standard except its own history - the seas are growing",
        "three great lakes anchor three great cultures; the interior belongs to no one",
        "narrow seas threading between continent-sized plateaus",
        "enough water for agriculture, in exactly the wrong places",
        "the wet season triples the map's blue and floods the calendars",
        "shallow inland seas whose shorelines wander decade to decade",
    ],
    4: [
        "sizeable seas divided by generous continents - a dry-but-liveable balance",
        "the water is regional: maritime cultures on the coasts, dust cultures inland",
        "four small oceans, none connected, each with its own navies and grudges",
        "a world of gulfs and inland seas, made for coastal trade",
        "water covers a third of the surface and dominates all of the poetry",
        "big lakes, small seas, and rivers that do the real work",
    ],
    5: [
        "half sea, half land, wholly contested at every shoreline",
        "a balanced world of continents and true oceans in rough parity",
        "island continents scattered across connected seas",
        "the great ocean owns one hemisphere; the land crowds into the other",
        "seas and landmasses interlock like puzzle pieces; every nation is coastal",
        "a temperate parity of land and water that the brochures call 'garden-like'",
    ],
    6: [
        "more sea than land; the continents feel like guests",
        "wide oceans broken by two great landmasses and ten thousand islands",
        "a maritime world - every city smells of salt and engine oil",
        "the oceans connect everything; the land merely interrupts them",
        "sixty percent water and a hundred percent naval tradition",
        "big weather off big oceans; the coasts build accordingly",
    ],
    7: [
        "a water-dominant world; its landmasses are large islands with delusions",
        "ocean as far as most people ever see, with land as the exception",
        "the continents are archipelago chains grown together",
        "sea lanes matter more than roads ever did here",
        "seventy percent ocean, and the fishing fleets outnumber the farms",
        "one modest continent and a planet of islands trailing away from it",
    ],
    8: [
        "an island world - the largest landmass crosses in a day's drive",
        "archipelagos everywhere; causeways and ferries are the national arteries",
        "drowned-continent geography: the highlands became islands and kept the culture",
        "a world of straits, tides and ten thousand harbours",
        "the land is scattered like crumbs on a blue table",
        "every island its own polity in spirit, whatever the government claims",
    ],
    9: [
        "almost all ocean; the land is a rounding error with real estate prices to match",
        "scattered volcanic islets and artificial platforms hold the entire population",
        "one archipelago worth the name; the rest of the land is navigational hazard",
        "the sea is the world - land is where you dry the nets",
        "ninety percent water; the mapmakers phone it in",
        "islands so scarce that reclamation engineering is the prestige profession",
    ],
    10: [
        "a true water world - no natural land breaks the surface anywhere",
        "world-ocean, pole to pole; the settlements float, submerge or stilt",
        "an endless sea with weather systems that circle the globe unopposed",
        "the entire world is ocean; 'inland' is not a concept here",
        "a planetary sea over drowned mountain ranges the sonar charts like scripture",
        "water without end - the horizon is the only geography",
    ],
}

# ---------------------------------------------------------------- population

POP_FLAVOUR = {
    0: [
        "empty of people; the wind has the world to itself",
        "uninhabited - visited, surveyed, claimed, and left",
        "no permanent population; whatever comes here, leaves",
        "a world without witnesses",
    ],
    1: [
        "a few dozen souls, every one of whom knows exactly who owes whom",
        "a double handful of inhabitants; the census is a group photo",
        "population measured in tens - one family, one feud, or one very odd choice",
        "a skeleton presence: caretakers, hermits, or someone's insurance requirement",
        "fewer people than a free trader's crew roster, and prouder for it",
        "tens of residents rattling around infrastructure built in hope of more",
    ],
    2: [
        "a few hundred people - a village with a planet attached",
        "everyone here fits in one hall, and on important nights, does",
        "population in the hundreds: one mayor, one doctor, one of most things",
        "a single settlement's worth of people and a wilderness of elbow room",
        "hundreds of inhabitants, most related, all opinionated",
        "an extended-family world; marriages here are logistics",
    ],
    3: [
        "a few thousand people clustered where the geography is kindest",
        "small-town population, frontier-sized territory",
        "thousands of souls - enough for factions, not enough for anonymity",
        "one real town and its stubborn outliers",
        "population in the low thousands, half of them somehow named after the founder",
        "enough people to staff the port, farm the valley, and disagree about both",
    ],
    4: [
        "tens of thousands - a proper colony now, whatever the old-timers say",
        "a modest population concentrated in a handful of towns",
        "enough people for a newspaper, a rivalry, and a planning committee",
        "the population crossed the threshold where everyone stopped knowing everyone, and mourns it",
        "tens of thousands, spread thin, bound by radio nets and shared debts",
        "a colony finding out what kind of place it intends to become",
    ],
    5: [
        "hundreds of thousands - cities in embryo, institutions taking root",
        "a population big enough to surprise its own founders' plans",
        "several small cities and the first real generational divide",
        "enough people that strangers exist, a fact the culture is still processing",
        "the labour shortage era just ended; the housing shortage era has begun",
        "a rising population with more ambition than infrastructure",
    ],
    6: [
        "millions of inhabitants - a settled world with history underfoot",
        "a few million people and the full apparatus of civilisation, slightly used",
        "population in the millions, identity still singular: one world, one story, mostly",
        "cities, provinces, and the comfortable friction between them",
        "millions strong, with emigration and immigration in constant argument",
        "a mature colony that has begun exporting people and importing problems",
    ],
    7: [
        "tens of millions - nations' worth of people under one sky",
        "a population large enough for real regional cultures and real regional grudges",
        "tens of millions, urbanising fast, romanticising the countryside faster",
        "enough people that the world sustains its own fashions, heresies and pop stars",
        "a big, busy population the port sees only the churn of",
        "the kind of population that has second cities with chips on their shoulders",
    ],
    8: [
        "hundreds of millions - a great world by any frontier measure",
        "a continental-scale civilisation with the confidence to match",
        "hundreds of millions of people and at least that many opinions on offworlders",
        "population dense enough that wilderness is a managed exhibit",
        "a heavyweight world whose domestic politics ripple across the subsector",
        "the census takes years and is wrong by a city either way",
    ],
    9: [
        "billions - the world hums day and night without pause",
        "a billions-strong hive of regions, classes, dialects and markets",
        "population at the billion scale; the port district alone outnumbers most worlds",
        "so many people that the world's problem is never labour, always coordination",
        "billions, stacked and sprawled, fed by miracles of logistics performed daily",
        "a demographic giant whose gravity bends the politics of every neighbour",
    ],
    10: [
        "tens of billions - humanity (or its neighbours) at full compression",
        "an ecumenopolis in the making; the countryside is a memory kept in parks",
        "tens of billions living in vertical geography - address includes altitude",
        "population so vast the world imports food, water, air and patience",
        "a tiered civilisation: your level is your class, your weather and your fate",
        "the kind of population that makes 'everyone' a statistical term",
    ],
}
for _k in (11, 12):
    POP_FLAVOUR[_k] = [
        "hundreds of billions - a population that redefines what a world is for",
        "a solid world-city; the planet is architecture with a core",
        "so many people that the census is a branch of astronomy",
        "a population sustained only by continuous interstellar logistics - and everyone knows it",
    ]

# ---------------------------------------------------------------- government

GOV_FLAVOUR = {
    0: [
        "kinship webs settle disputes by mediation and feud",
        "no authority beyond ad-hoc town meetings when crisis forces one",
        "extended clans each run their own affairs; outsiders deal clan by clan",
        "a working anarchy of handshake law and long memories",
        "customary law administered by respected elders who deny administering anything",
        "each homestead is sovereign in practice; cooperation is seasonal and voluntary",
        "no government, but an etiquette so strict it might as well be one",
        "affairs are managed by whoever shows up to the meeting, which is the trick of it",
        "a stateless society that treats the word 'taxation' as foreign profanity",
        "order is kept by reputation: to be untrusted here is to be exiled in place",
    ],
    1: [
        "a single corporation owns the charter, the port and every habitat",
        "a resource-extraction franchise runs the world as a depreciating asset",
        "the Company is employer, landlord, court and church in all but name",
        "a board of directors lightyears away sets policy; the site manager sets reality",
        "wholly-owned: wages in scrip, housing in units, dissent in writing to HR",
        "a startup colony still on its founders' equity and enthusiasm",
        "a venerable chartered company, its founding patent framed in the port lobby",
        "three subsidiaries in a trenchcoat pretending to be a civil administration",
        "the corporation is benevolent, efficient, and owns the word 'benevolent'",
        "management rotates offworld every two years; the union's memory does not",
        "a company world in receivership - the creditors' committee is the de facto senate",
    ],
    2: [
        "every adult votes on everything via the network; politics is exhausting and constant",
        "citizen assemblies chosen by lot decide policy in rowdy public sessions",
        "direct democracy with mandatory participation - abstention is a misdemeanour",
        "referenda decide everything, including, twice so far, whether to keep doing referenda",
        "policy is drafted by petition and passed by planetary vote; lawyers write the questions",
        "a town-meeting world scaled up by technology and held together by caffeine",
        "deliberative juries, chosen by lottery, sit for a season and then flee public life",
        "the franchise is earned by service, and the arguments about 'service' never end",
        "every ordinance carries the vote tally that passed it, as scripture cites verse",
        "government by plebiscite, opposition by turnout campaign",
    ],
    3: [
        "a closed circle of founding families co-opts its own replacements",
        "the Directorate answers to nobody and recruits only from itself",
        "old money runs everything behind a facade of civic institutions",
        "seven houses hold the world in trust for themselves",
        "an aristocracy of the first landing - the Ship Roll decides who matters",
        "the oligarchs compete viciously among themselves and close ranks instantly against everyone else",
        "a self-electing senate whose vacancies outnumber its funerals only slightly",
        "power passes by adoption; the great families collect talent like art",
        "the constitution is beautiful and the twelve people who matter have never read it",
        "an inner circle so discreet that naming its members is a parlour game and a career risk",
    ],
    4: [
        "elected representatives, machine politics, and a permanent campaign season",
        "a parliament of regional delegates locked in coalition horse-trading",
        "two entrenched parties alternate power and split the patronage",
        "a young legislature, earnest and loud, still writing precedents in wet ink",
        "representative democracy with a civil service that considers elections weather",
        "the assembly is elected fairly and lobbied ferociously",
        "proportional representation has produced nine parties and one permanent negotiation",
        "an elected presidency checked by courts, chambers, and cussedness",
        "democracy functions; cynicism about it is the national sport and its immune system",
        "every district sends a delegate and a grievance, in that order of size",
    ],
    5: [
        "engineers hold rank; competence oaths bind vassal-specialists to guild-lords",
        "technical guilds hold hereditary charters over infrastructure fiefs",
        "whoever maintains the life support gives the orders, in law as in fact",
        "a pyramid of licensed expertise: mastery is title, certification is nobility",
        "the Fusion Barons keep the lights on and the loyalty flowing",
        "feudal contracts bind every technician to a patron and every patron to the Works",
        "rank follows the maintenance schedule - the reactor's chief engineer outranks the mayor",
        "guild-lords exchange apprentices as other courts exchange hostages",
        "an aristocracy of technical dynasties, each married to its machinery",
        "fealty is sworn to systems, not persons: the Grid, the Water, the Vats",
    ],
    6: [
        "an offworld power appoints the governor; locals staff everything below",
        "a puppet council rubber-stamps directives from somewhere else",
        "occupation has calcified into administration; resentment is quiet but total",
        "a colonial office runs the world by memo, three weeks' lag and counting",
        "the garrison is polite, permanent, and in charge",
        "administered 'temporarily' under a mandate now older than anyone enforcing it",
        "the resident-general holds veto power and uses it just often enough",
        "local government exists in full ceremonial detail and no actual authority",
        "a client regime balancing its patron's demands against its people's memory",
        "the flag on the government house is not the flag in most hearts",
    ],
    7: [
        "rival states share the world and agree on almost nothing",
        "a patchwork of statelets, borders drawn in old grudges",
        "two great blocs and a scatter of neutrals; the port is contested ground",
        "five nations, three alphabets, two calendars, one planet - barely",
        "a cold war with pleasant beaches: tourism and espionage share hotels",
        "the world government exists as a letterhead all parties ignore jointly",
        "dozens of microstates federated only by the need to disagree formally",
        "a partitioned world; the ceasefire line has fossilised into geography",
        "each polity claims the whole planet and administers its share of the paperwork",
        "the balance of power is the only planetary institution, and it is carefully maintained",
    ],
    8: [
        "forms, permits and queues; the bureaucracy is slow but incorruptible-ish",
        "government by career administrators following procedures nobody remembers writing",
        "everything is legal, licensed, logged - and glacial",
        "the civil service outlasted three constitutions and expects to outlast yours",
        "a meritocratic mandarinate recruited by brutal examination",
        "the ministries compete like noble houses, with better filing",
        "administration is the local art form; the annual budget is literature",
        "nothing is forbidden that is properly permitted, and nothing is ever properly permitted",
        "the state runs on precedent; innovation requires a form that does not yet exist",
        "competent, colourless, and everywhere - government as ambient infrastructure",
    ],
    9: [
        "an opaque apparatus processes citizens like cargo manifests",
        "decisions emerge from the ministries; no individual is ever responsible",
        "the state is a machine that no one person can be said to steer",
        "policy is announced, never explained; appeal is a department, not a possibility",
        "the bureaucracy has metastasised into the economy, the culture and the architecture",
        "citizens are files; the well-managed file lives a quiet life",
        "an administrative labyrinth in which even the administrators file requests to navigate",
        "the government's org chart is classified, possibly from itself",
        "rule by directive: numbered, binding, and unsigned",
        "the system works, in the sense that a glacier works",
    ],
    10: [
        "one leader, adored and untouchable, holds it together by force of personality",
        "the Founder's face is on everything; succession is the unaskable question",
        "a war hero turned president-for-life, still genuinely popular - mostly",
        "the Liberator rules by acclamation, annually renewed, never counted",
        "a dictator with the common touch and an uncommon security detail",
        "her speeches are holidays; her silences are policy",
        "the strongman is charming, tireless, and has already outlived two heirs-apparent",
        "a reformer who seized power to fix things and found the power the thing he fixed",
        "government by charisma: the institutions exist to schedule his appearances",
        "the leader is loved, the regime is feared, and no one may point out the difference",
        "a prophet-president whose cabinet exists to interpret the morning's remarks",
    ],
    11: [
        "a grey successor rules through the security services the last leader built",
        "the strongman is gone; his apparatus grinds on under a committee nobody loves",
        "rule by the second-in-command who outlasted everyone more interesting",
        "an accountant of a tyrant: efficient, joyless, and very hard to overthrow",
        "the general who ended the chaos, and stayed to prevent all further history",
        "power rests on three pillars: the army, the files, and fatigue",
        "a caretaker regime, decades into its fourth 'transition period'",
        "the ruler inspires no songs and permits no others",
        "unloved and unbothered - the regime measures loyalty in compliance, not applause",
        "the leader's portrait hangs everywhere, straight, dusted, and ignored",
    ],
    12: [
        "a revolutionary vanguard rules in the name of a cause it half-remembers",
        "a junta of celebrated officers, each watching the others",
        "an inner party bound by shared ideology and shared guilt",
        "the Movement's founding generation clings on; the second generation drafts eulogies and plans",
        "a charismatic collective: the Twelve appear together, always, or not at all",
        "rule by the heroes of the Emergency, who ensure the Emergency never quite ends",
        "a brotherhood of liberators who trust each other with everything except succession",
        "the Council of the Faith-in-Progress, equal parts seminary and general staff",
        "an oligarchy welded together by one great shared deed it cannot afford examined",
        "the founders' portraits smile down in committee - governance by remembered consensus",
    ],
    13: [
        "scripture is statute; the clergy staff the courts and the customs desk",
        "a prophet's heirs govern; doctrine settles what evidence cannot",
        "religious law, enforced with sincerity and surveillance in equal measure",
        "the Temple owns the calendar, the courts and the concept of doubt",
        "a theocratic bureaucracy: salvation has forms, in triplicate",
        "rule by the Interpreting Council, whose readings are law and whose schisms are coups",
        "the faith is administered like a utility - metered, billed, and occasionally cut off",
        "god's law, man's enforcement, and a growing gap between them that no one names",
        "an inquisitorial state, more curious than cruel, so far",
        "the hierarchy is open to all believers, which is the genius and the trap of it",
    ],
    14: [
        "god's regent rules absolutely; heresy and treason are the same offence",
        "the temple owns the land, the water and the calendar",
        "an infallible pontiff-sovereign whose word rewrites law overnight",
        "the Living Voice speaks rarely; the world holds its breath accordingly",
        "divine autocracy in full ceremony - the throne room is a cathedral is a court",
        "the god-sovereign is chosen by sign and portent, managed by those who read them",
        "one sacred ruler, one truth, one very busy office of interpretation",
        "the hierarch's blessing is licence, passport and pardon; its absence is a wall",
        "a sacral monarchy where the coronation rite matters more than the constitution ever could",
        "heaven's mandate, enforced locally",
    ],
    15: [
        "total surveillance, total mobilisation; the state admits no private sphere",
        "an anonymous oligarchy enforces orthodoxy through block wardens and informers",
        "the Party is everywhere; the cameras are only its reminder",
        "a sealed elite runs a sealed society; even the propaganda is need-to-know",
        "every citizen has a file, a quota and a designated optimism",
        "the regime perfected control and now suffers only from success",
        "rule by the Committee, whose membership is secret and whose reach is not",
        "an engineered society: hobbies are licensed, friendships are registered",
        "the state owns the truth outright and leases it back at rates",
        "totalitarian and tidy - the trains run on time to destinations you don't choose",
    ],
}

# ---------------------------------------------------------------- law

LAW_FLAVOUR = {
    0: [
        "disputes end in duels or don't end",
        "the port posts its own rules at the gate because nobody else will",
        "visitors are startled by open-carry everything",
        "no law but custom, and custom is armed",
        "contracts are enforced by reputation and, failing that, by relatives",
        "the only universal crime is cowardice in a bargain",
        "an honour culture with excellent manners and short probate",
    ],
    1: [
        "the law exists chiefly to keep the truly apocalyptic toys off the streets",
        "anything short of military hardware is nobody's business",
        "one statute, broadly written, rarely invoked, universally understood",
        "the sheriff cares about two things; everything else is between you and yours",
        "law so light it is mistaken for absence until, memorably, it isn't",
        "regulation ends where the port fence does",
        "the courts convene when needed, which is roughly annually",
    ],
    2: [
        "enforcement is personal, local and negotiable",
        "constables know everyone and arrest almost no one",
        "the law is real but distant; frontier custom fills the gaps",
        "magistrates ride circuit; justice arrives quarterly, with the mail",
        "energy weapons raise eyebrows; everything else raises prices",
        "the law is a neighbour here - helpful, nosy, and slow to anger",
        "rules are posted politely and enforced conversationally",
    ],
    3: [
        "military hardware draws attention; a sidearm draws a nod",
        "the police are few, armed, and famous individually",
        "law enforcement is a part-time job done by full-time personalities",
        "town limits mark the legal frontier - inside, rules; outside, advice",
        "the annual weapons audit is also the annual fair",
        "practical law: no automatics, no artillery, no exceptions for good stories",
        "justice is quick, local, and appealable only to geography",
    ],
    4: [
        "licences and permits for the serious hardware; the paperwork is genuinely checked",
        "police are professional, armed and unhurried",
        "the law arrives within the hour and expects to be obeyed by then",
        "weapons above a calibre live in gun clubs and armouries, mostly",
        "enforcement is even-handed in the cities and interpretive elsewhere",
        "the rules are posted, enforced, and occasionally waived for a consideration",
        "a licensing regime old enough to have loopholes with historical societies",
    ],
    5: [
        "concealable weapons are contraband; the pat-down at the port is ritual",
        "the police are visible, courteous, and backed by response teams nobody sees",
        "personal firearms need papers; papers need patience; patience needs connections",
        "law-abiding here means documented - carry your permits like a second skin",
        "checkpoints at district lines, cursory for locals, thorough for hulls-fresh spacers",
        "mid-weight law: enough order to be safe, enough discretion to be human",
        "the licensing office is the true gatekeeper of local society",
    ],
    6: [
        "firearms are for registered collections and rural pests; stunners for everyone else",
        "the police carry stunners and the law carries weight",
        "weapon lockers at the port gate do brisk, bonded business",
        "enforcement is systematic - cameras first, officers second, questions third",
        "the law is a presence: patrols, permits, and polite unblinking attention",
        "most citizens have never seen a working firearm outside a museum case",
        "carrying draws a fine; brandishing draws a cell; using draws a decade",
    ],
    7: [
        "even shotguns are contraband now; the smugglers' margins thank the legislature",
        "the disarmament statutes are old, settled and strictly meant",
        "police response is fast, layered, and rehearsed",
        "weapon law is absolute in the cities and merely emphatic beyond them",
        "the ban list grows annually; the appeals process is decorative",
        "hunting is licensed theatre; self-defence is a state monopoly",
        "the law counts blades over a hand-span, and someone's job is measuring",
    ],
    8: [
        "blades and stunners join the ban list; enforcement is thorough and unembarrassed",
        "checkpoints, registrations, and contraband sweeps at the port",
        "plainclothes officers outnumber uniformed ones",
        "the law regulates tools, gatherings, broadcasts and tone",
        "citizens are searched routinely and compensated politely for the time",
        "a kitchen knife has papers here",
        "security theatre with a full production budget and no interval",
    ],
    9: [
        "any weapon outside the home is a career-ending discovery",
        "visitors are fingerprinted, geofenced and politely warned",
        "the law presumes, inspects and archives; innocence is a filing status",
        "off-porters travel with escorts described as 'guides'",
        "compliance is total in public and priced accordingly in private",
        "the state's monopoly on force is enforced with the state's whole force",
        "even the police sign out their sidearms per shift, in triplicate",
    ],
    10: [
        "movement permits, block wardens, curfews; offworlders are escorted",
        "every transaction is logged and every gathering licensed",
        "the security services are the true government, whatever the constitution says",
        "possessions are inventoried at entry and audited at exit",
        "conversation with foreigners is a reportable event, and reported",
        "the law does not restrict the citizen; it defines the citizen",
        "surveillance is not a policy here - it is the architecture",
    ],
}

# ---------------------------------------------------------------- tech level

TL_FLAVOUR = {
    0: [
        "stone, bone, hide and fire - toolmaking at its first dawn",
        "neolithic craft of surprising sophistication and no metal at all",
        "a pre-metal culture whose stonework will outlast every visitor",
    ],
    1: [
        "bronze-age metallurgy and monumental ambition",
        "iron ploughs, oxcarts, and empires of grain and levy",
        "classical-era engineering: aqueducts, roads, and mathematics done in sand",
    ],
    2: [
        "sail and gunpowder; the printing houses are changing everything",
        "renaissance craft - clockwork, cannon, and cartography with sea monsters",
        "an age of guilds, galleons and the first uncomfortable telescopes",
    ],
    3: [
        "steam and steel; the railways are stitching the world together",
        "early industry - mills, muskets and mines, with all the smoke that implies",
        "the beginning of mass everything: production, literacy, warfare",
    ],
    4: [
        "internal combustion, radio, and flight in its reckless adolescence",
        "an electrified world of telegraph empires and assembly lines",
        "early-industrial might: dreadnoughts at sea, biplanes above, arguments everywhere",
    ],
    5: [
        "atomics, television and the first computers filling entire floors",
        "mid-industrial tech - jet aircraft, mass media, plastics in everything",
        "the missile age: enormous power, narrow margins, black-and-white broadcasts",
    ],
    6: [
        "spaceflight in its first generation - capsules, boosters and nerve",
        "transistorised and orbiting: satellites up, computers shrinking",
        "nuclear power, early networks, and probes flung at the neighbouring worlds",
    ],
    7: [
        "a wired world on the edge of space - orbital shuttles and global networks",
        "pre-stellar tech: fusion prototypes, arcologies on the drawing board",
        "information-age industry with launch capacity and ambitions to match",
    ],
    8: [
        "fusion power and true orbital industry; the system is theirs, slowly",
        "gravitic tech in its infancy - the first floating vehicles draw crowds",
        "a system-faring civilisation waiting on the jump drive",
    ],
    9: [
        "the first jump drives - interstellar reach, barely, expensively",
        "early stellar tech: grav vehicles common, fusion cheap, stars reachable",
        "a civilisation newly interstellar and still astonished by it",
    ],
    10: [
        "established stellar tech - reliable jump-1, orbital habitats, mature gravitics",
        "solid interstellar-age industry; nothing exotic, everything dependable",
        "the tech base of a thousand settled worlds: proven, portable, repairable",
    ],
    11: [
        "advanced stellar tech - jump-2 yards, true AI at the threshold",
        "sophisticated manufacturing; their exports set the subsector standard",
        "a tech base other worlds send their students to",
    ],
    12: [
        "average imperial tech - grav cities, weather control, jump-3 capability",
        "the comfortable plateau of mature interstellar civilisation",
        "cutting-edge medicine, casual gravitics, and shipyards of real consequence",
    ],
    13: [
        "above-standard tech: cloning vats, battle dress, minds part-machine",
        "a high-technology world whose exports need export licences",
        "engineering a generation ahead of its neighbours, and priced accordingly",
    ],
    14: [
        "near the imperial maximum - fliers think, buildings heal, borders scan",
        "technology advanced enough to look effortless, which is the expensive part",
        "one of the great technical worlds; its patents are a form of territory",
    ],
    15: [
        "the imperial maximum - technology at the edge of what is licensed to exist",
        "bleeding-edge everything; half the economy is research, the other half security",
        "a pinnacle tech world where yesterday's prototype is tomorrow's export scandal",
    ],
}
for _k in range(16, 20):
    TL_FLAVOUR[_k] = [
        "technology beyond the recognised maximum - quietly studied by everyone's intelligence services",
        "post-imperial tech that should not exist and inconveniently does",
        "a tech base officially described as 'anomalous' and unofficially as 'worrying'",
    ]


def clamp_pick(table, key):
    """Return the table list for key, clamping to the nearest defined value."""
    if key in table:
        return table[key]
    ks = sorted(k for k in table if isinstance(k, int))
    return table[min(ks, key=lambda k: abs(k - key))]
